### ISSUE TITLE
Не могу создать пользователя

### ISSUE THREAD

**Issue by SmirnIL** [CLOUDdotRu/evo-terraform#1]
При создании нового пользователя получаю ошибку "Failed to create user"
<img width="591" alt="image" src="https://github.com/CLOUDdotRu/evo-terraform/assets/44359079/a3e2177a-e9a0-4db2-a492-7017c485909d">
Код брал из примера.

**Comment by mac-ru** [comment]
Судя по всему управление идёт через CloudPlatform, которому необходима установка customer_id 
https://github.com/CLOUDdotRu/evo-terraform/blob/main/examples/main.tf#L15

> NOTE: Это обязательный параметр при использованиии CloudPlatform
>   customer_id = "<HIDDEN>"

![image](https://github.com/user-attachments/assets/701cb68a-1cd5-4c0e-a878-91990288d255)

**Comment by serkopa** [comment]
для работы с провайдером личного кабинета, поле customer_id является обязательным
