### ISSUE TITLE
Ошибка в документации data "cloudru_evolution_image"

### ISSUE THREAD

**Issue by devmiroshnikovm** [CLOUDdotRu/evo-terraform#10]
<img width="404" alt="Screenshot 2024-05-28 at 16 31 11" src="https://github.com/CLOUDdotRu/evo-terraform/assets/118925977/7c614f37-b9ff-42d6-be38-43d12a63c264">

https://github.com/CLOUDdotRu/evo-terraform/blob/bae6dd03d513dc2a78cf09b0873eeb32143a8934/examples/evolution/simple/datasource/data_image.tf#L8

`data.cloudru_evolution_image.images: Reading...
data.cloudru_evolution_image.images: Read complete after 0s [id=resources]

Changes to Outputs:
  + images      = {
      + filter    = [
          + {
              + availability_zone_id = ""
              + name                 = "Ubuntu-22.04"
            },
        ]
      + id        = "resources"
      + resources = []
    }
  - my_image_id = "resources" -> null`

нужно поменять в примере на  ubuntu-22.04

**Comment by mac-ru** [comment]
Подтверждаю - образы идут
            name               = "ubuntu-18.04"
            name               = "ubuntu-22.04"
            name               = "ubuntu-20.04"
            name               = "mean-ubuntu-22.04"
            name               = "nginx-ubuntu-22.04"
            name               = "nodejs-ubuntu-22.04-market"
