### ISSUE TITLE
Не смог отобразить подсеть

### ISSUE THREAD

**Issue by SmirnIL** [CLOUDdotRu/evo-terraform#2]
Пытаюсь отобразить Default-подсеть:
<img width="993" alt="image" src="https://github.com/CLOUDdotRu/evo-terraform/assets/44359079/68e0082c-8ddc-40f2-a248-c2bf34312c6e">
Использую код:

```
data "cloudru_evolution_available_subnet" "subnets" {
  # NOTE: Это обязательный параметр
  filter {
    # NOTE: это опциональный параметр, по умолчанию используется project_id указанный в секции provider
    # project_id = "00000000-0000-0000-0000-000000000000"
    # NOTE: Это обязательный параметр
    subnet_mask = 24
    # NOTE: Это обязательный параметр
    base_subnet_address = "192.168.1.0/24"
  }
}

output "filtered_available_subnets" {
  value = data.cloudru_evolution_available_subnet.subnets.resources
}
```

В выводе ничего нет:
<img width="923" alt="image" src="https://github.com/CLOUDdotRu/evo-terraform/assets/44359079/a5138da4-f3c3-4a8d-9bd7-f8f92a8b6595">

**Comment by mac-ru** [comment]
![image](https://github.com/user-attachments/assets/1f1a81c8-a418-4608-a9ad-6c68198ea242)
Судя по всему ошибка в документации.

**Comment by mac-ru** [comment]
Хотя нет, судя по доке - сейчас фильтр не обязателен

**Comment by serkopa** [comment]
Исправлено в последней версии
