### ISSUE TITLE
Не смог создать subnet

### ISSUE THREAD

**Issue by SmirnIL** [CLOUDdotRu/evo-terraform#4]
При попытке создать subnet получаю ошибку:

```
│ Error: failed to create subnet
│ 
│   with cloudru_evolution_subnet.test_subnet,
│   on main.tf line 92, in resource "cloudru_evolution_subnet" "test_subnet":
│   92: resource "cloudru_evolution_subnet" "test_subnet" {
│ 
```
`terraform plan` ошибок не выдает.

Использую код:

```
resource "cloudru_evolution_tag" "test_tag" {

  name = "test"
  color = "red"
  project_id = "<projectId>"
}

resource "cloudru_evolution_subnet" "test_subnet" {

  name = "test"
  subnet_address = "192.168.10.0/24"

  availability_zone {
    id = local.demo_az.id
  }
  project {
    id = "<projectId>"
  }
  tags {
    id = resource.cloudru_evolution_tag.test_tag.id
  }
}
```

**Comment by mac-ru** [comment]
name = "test" в subnet не правильно, т.к. судя по доке должно быть минимум 7 символов.

resource "cloudru_evolution_subnet" "test_subnet" {
  name = "test_subnet"
  subnet_address = "192.168.10.0/24"
  project_id = "690f977b-1cb5-4904-807c-1b2842405e27"
  availability_zone {
    id = "7c99a597-8516-494f-a2c7-d7377048681e"
  }
}
Также не смог создать

**Comment by serkopa** [comment]
Поле default_gateway является обязательным. Исправлено в документации
