### ISSUE TITLE
Параметр description в nat_gateway

### ISSUE THREAD

**Issue by SmirnIL** [CLOUDdotRu/evo-terraform#5]
В примере для cloudru_evolution_nat_gateway параметр description указан, как опциональный, но терраформ выдает ошибку без него.

**Comment by mac-ru** [comment]
Нет, опциональный, создалось окей
![image](https://github.com/user-attachments/assets/0d4973ab-aa8a-41f4-aa8b-f23595d9cddd)

cat nat_gw.tf | egrep -v "^ *#|^$"

resource "cloudru_evolution_nat_gateway" "gateway" {
  name = "gateway"
  availability_zone {
    id = "7c99a597-8516-494f-a2c7-d7377048681e"
  }
  nat_type = "Public sNAT"
}
